# server
server:
  port: 9999
# spring
spring:
  application:
    name: epoch-demo-starter-mybatis
  # data source
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.url:localhost:3306}/epoch-iam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: marshal1234!
# oauth2
security:
  oauth2:
    client:
      accessTokenUri: ${auth.url:http://localhost:8020}/oauth/token
      userAuthorizationUri: ${auth.url:http://localhost:8020}/oauth/authorize
      clientId: EPOCH
      clientSecret: 123456
    resource:
      userInfoUri: ${auth.url:http://localhost:8020}/user
# health check management
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway
# log
logging:
  level:
    root: info
    org.epoch: debug
# epoch
epoch:
  security:
    enable-auth: true
